nmap <buffer> r <Plug>(fern-action-reload)
nmap <buffer> <C-j> <C-d>
nmap <buffer> <C-k> <C-u>
nmap <buffer> <Tab> <Plug>(fern-action-mark)
nmap <buffer> <C-t> <Plug>(fern-action-open:tabedit)
nmap <buffer> <C-x> <Plug>(fern-action-open:split)
nmap <buffer> <C-v> <Plug>(fern-action-open:vsplit)
nmap <buffer> <C-l> <Plug>(fern-action-enter)
nmap <buffer> <C-r> <Plug>(fern-action-redraw)
